INSERT INTO blogful_articles (title, date_published, content)
VALUES
    ('Ferns', now() - '1 days'::INTERVAL, 'They are usually green.'),
    ('Trees', now() - '2 days'::INTERVAL, 'I would be very happy if we planted more of them'),
    ('Oceans', now() - '9 days'::INTERVAL, 'Our oceans are dying and people arnt mad enough about that. Why?'),
    ('Land Use', now() - '7 days'::INTERVAL, 'We are exploiting the planet... mostly just the Koch brothers and people like them. They are evil manifested in human form. Look them up. No seriuosly... just give them a google.'),
    ('Indigenous peoples', now() - '16 days'::INTERVAL, 'Give them back their rights and land!'),
    ('Western Culture', now() - '25 days'::INTERVAL, 'Will be the death of our planet'),
    ('Rivers', now() - '21 days'::INTERVAL, 'We must fight to keep our rivers clean'),
    ('Clouds', now() - '11 days'::INTERVAL, 'Literally disappearing in the pacific and rising so that we have less rain fall'),
    ('Plastic', now() - '15 days'::INTERVAL, 'You probably ate plastic today cause it is now imbedded in our food chain. Good job humans.'),
    ('Fossil Fuels', now() - '23 days'::INTERVAL, 'Divest'),
    ('Clean Energy', now() - '28 days'::INTERVAL, 'Invest'),
    ('Fast Fashion', now() - '29 days'::INTERVAL, 'Contributes huge amounts of waste and green house gases. Terrible Terrible Industry'),
    ('Meat Consumption', now() - '12 days'::INTERVAL, 'If you care about yourself, others, animals, the planet and the next generation... maybe do not eat meat any more you freaking twinky'),
    ('Awareness', now() - '13 days'::INTERVAL, 'Does not exist in mainstream western culture'),
    ('Over Fishing', now() - '3 days'::INTERVAL, 'Thats a problem... fix it'),
    ('Circular Economy', now() - '18 days'::INTERVAL, 'Its a viable model for our economy'),
    ('Interconnectivity', now() - '17 days'::INTERVAL, 'Everything is more complex than we can even imagine. My mind is blown every day'),
    ('Ego', now() - '15 days'::INTERVAL, 'What a joke'),
    ('Meditation', now() - '20 days'::INTERVAL, 'It is pretty great.. still anxious though'),
    ('Software Enginering', now() - '18 days'::INTERVAL, 'How I plan on making a positive impact regarding the UNs SDGs'),
    ('Is that twenty?', now() - '25 days'::INTERVAL, 'I think so.')